export const Icons = {
  Dashboard: 'material-symbols:dashboard-outline',
  AgentOverview: 'material-symbols:tune',
  Claims: 'material-symbols:description',
  Quote: 'material-symbols:chat-bubble-outline',
  Recommendation: 'fluent:star-emphasis-24-regular',
  Setting: 'material-symbols:settings',
  Success: 'material-symbols:check-circle',
  Warning: 'mdi:alert-outline',
  Error: 'cuida:alert-outline',
  Info: 'material-symbols:info',
  Failed: 'mingcute:warning-line',
  InProgress: 'hugeicons:loading-02',
  Menu: 'material-symbols:menu',
  Notification: 'material-symbols:notifications',
  ChevronLeft: 'material-symbols:chevron-left',
  ChevronRight: 'material-symbols:chevron-right',
  Cancel: 'material-symbols:cancel-outline-rounded',
  Loading: 'mingcute:loading-fill',
  Activity: 'tabler:activity',
} as const;
